# Generated by Django 5.2.17 on 2026-08-31 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodenart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Bodenart',
                'verbose_name_plural': 'Bodenarten',
            },
        ),
        migrations.CreateModel(
            name='Pflanze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('botanischer_name', models.CharField(blank=True, max_length=120, verbose_name='botanischer Name')),
                ('lichtbedarf', models.IntegerField(choices=[(1, 'schattig'), (2, 'halbschattig'), (3, 'hell, ohne direkte Sonne'), (4, 'vollsonnig')], verbose_name='Lichtbedarf')),
                ('temperaturuntergrenze', models.IntegerField(help_text='Tiefste Temperatur, die die Pflanze dauerhaft ohne Schaden uebersteht.', verbose_name='vertraegt Temperaturen bis (Grad Celsius)')),
                ('feuchtigkeitsbedarf', models.IntegerField(choices=[(1, 'trocken'), (2, 'normal'), (3, 'feucht')], verbose_name='Feuchtigkeitsbedarf')),
                ('giftig', models.BooleanField(default=False, verbose_name='giftig')),
                ('wasserbedarf', models.IntegerField(choices=[(1, 'trocken'), (2, 'normal'), (3, 'feucht')], verbose_name='Wasserbedarf')),
                ('endwuchshoehe_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Endwuchshoehe in cm')),
                ('status', models.CharField(choices=[('wunsch', 'auf der Wunschliste'), ('bestand', 'im Bestand')], default='wunsch', max_length=10, verbose_name='Status')),
                ('besitzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pflanzen', to=settings.AUTH_USER_MODEL)),
                ('geeignete_bodenarten', models.ManyToManyField(related_name='pflanzen', to='plants.bodenart', verbose_name='geeignete Bodenarten')),
            ],
            options={
                'verbose_name': 'Pflanze',
                'verbose_name_plural': 'Pflanzen',
            },
        ),
        migrations.CreateModel(
            name='Pflegevorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taetigkeit', models.CharField(choices=[('giessen', 'Gießen'), ('duengen', 'Düngen'), ('umtopfen', 'Umtopfen'), ('schneiden', 'Zurückschneiden'), ('vermehren', 'Vermehren')], max_length=15, verbose_name='Tätigkeit')),
                ('intervall_tage', models.PositiveIntegerField(verbose_name='Intervall in Tagen')),
                ('hinweis', models.CharField(blank=True, max_length=200, verbose_name='Hinweis')),
                ('pflanze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pflegevorlagen', to='plants.pflanze')),
            ],
            options={
                'verbose_name': 'Pflegevorlage',
                'verbose_name_plural': 'Pflegevorlagen',
            },
        ),
        migrations.CreateModel(
            name='Pflegeaufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faelligkeit', models.DateField(verbose_name='faellig am')),
                ('erledigt_am', models.DateField(blank=True, null=True, verbose_name='erledigt am')),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='plants.pflegevorlage')),
            ],
            options={
                'verbose_name': 'Pflegeaufgabe',
                'verbose_name_plural': 'Pflegeaufgaben',
                'ordering': ['faelligkeit'],
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Bezeichnung')),
                ('art', models.CharField(choices=[('innen', 'Innenraum'), ('balkon', 'Balkon'), ('garten', 'Garten')], max_length=10, verbose_name='Art')),
                ('lichtangebot', models.IntegerField(choices=[(1, 'schattig'), (2, 'halbschattig'), (3, 'hell, ohne direkte Sonne'), (4, 'vollsonnig')], verbose_name='Lichtangebot')),
                ('minimaltemperatur', models.IntegerField(help_text='Tiefster Wert, der am Standort im Jahresverlauf erreicht wird.', verbose_name='niedrigste Temperatur in Grad Celsius')),
                ('luftfeuchtigkeit', models.IntegerField(choices=[(1, 'trocken'), (2, 'normal'), (3, 'feucht')], verbose_name='Luftfeuchtigkeit')),
                ('erreichbar_fuer_kinder_haustiere', models.BooleanField(default=False, help_text='Angehakt, wenn Kinder oder Haustiere an die Pflanzen herankommen.', verbose_name='fuer Kinder oder Haustiere erreichbar')),
                ('besitzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standorte', to=settings.AUTH_USER_MODEL)),
                ('bodenart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.bodenart', verbose_name='Bodenart')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
            },
        ),
        migrations.AddField(
            model_name='pflanze',
            name='standort',
            field=models.ForeignKey(blank=True, help_text='Nur bei Pflanzen im Bestand gesetzt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pflanzen', to='plants.standort', verbose_name='Standort'),
        ),
        migrations.AddConstraint(
            model_name='standort',
            constraint=models.UniqueConstraint(fields=('besitzer', 'name'), name='standortname_je_benutzer'),
        ),
    ]
