# Generated by Django 5.2.17 on 2026-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pflanze',
            name='lichtbedarf',
            field=models.IntegerField(choices=[(1, 'sehr schattig'), (2, 'schattig'), (3, 'halbschattig'), (4, 'hell'), (5, 'sonnig')], verbose_name='Lichtbedarf'),
        ),
        migrations.AlterField(
            model_name='pflanze',
            name='wasserbedarf',
            field=models.IntegerField(choices=[(1, 'sehr gering'), (2, 'gering'), (3, 'mittel'), (4, 'hoch'), (5, 'sehr hoch')], verbose_name='Wasserbedarf'),
        ),
        migrations.AlterField(
            model_name='standort',
            name='lichtangebot',
            field=models.IntegerField(choices=[(1, 'sehr schattig'), (2, 'schattig'), (3, 'halbschattig'), (4, 'hell'), (5, 'sonnig')], verbose_name='Lichtangebot'),
        ),
    ]
