# Generated by Django 5.2.17 on 2026-09-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_pflanze_lichtbedarf_alter_pflanze_wasserbedarf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodenart',
            options={'ordering': ['name'], 'verbose_name': 'Bodenart', 'verbose_name_plural': 'Bodenarten'},
        ),
        migrations.AlterModelOptions(
            name='pflanze',
            options={'ordering': ['art__name'], 'verbose_name': 'Pflanze', 'verbose_name_plural': 'Pflanzen'},
        ),
        migrations.AlterModelOptions(
            name='standort',
            options={'ordering': ['name'], 'verbose_name': 'Standort', 'verbose_name_plural': 'Standorte'},
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='botanischer_name',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='endwuchshoehe_cm',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='feuchtigkeitsbedarf',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='geeignete_bodenarten',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='giftig',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='lichtbedarf',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='temperaturuntergrenze',
        ),
        migrations.RemoveField(
            model_name='pflanze',
            name='wasserbedarf',
        ),
        migrations.AddField(
            model_name='pflanze',
            name='eigener_name',
            field=models.CharField(blank=True, help_text='Optional, zur Unterscheidung mehrerer Exemplare, z. B. "die große im Flur".', max_length=80, verbose_name='eigene Bezeichnung'),
        ),
        migrations.AddField(
            model_name='pflanze',
            name='notiz',
            field=models.TextField(blank=True, verbose_name='Notiz'),
        ),
        migrations.AlterField(
            model_name='pflegeaufgabe',
            name='faelligkeit',
            field=models.DateField(verbose_name='fällig am'),
        ),
        migrations.AlterField(
            model_name='standort',
            name='erreichbar_fuer_kinder_haustiere',
            field=models.BooleanField(default=False, help_text='Angehakt, wenn Kinder oder Haustiere an die Pflanzen herankommen.', verbose_name='für Kinder oder Haustiere erreichbar'),
        ),
        migrations.CreateModel(
            name='Pflanzenart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('botanischer_name', models.CharField(blank=True, max_length=120, verbose_name='botanischer Name')),
                ('lichtbedarf', models.IntegerField(choices=[(1, 'sehr schattig'), (2, 'schattig'), (3, 'halbschattig'), (4, 'hell'), (5, 'sonnig')], verbose_name='Lichtbedarf')),
                ('temperaturuntergrenze', models.IntegerField(help_text='Tiefste Temperatur, die die Pflanze dauerhaft ohne Schaden übersteht.', verbose_name='verträgt Temperaturen bis (Grad Celsius)')),
                ('feuchtigkeitsbedarf', models.IntegerField(choices=[(1, 'trocken'), (2, 'normal'), (3, 'feucht')], verbose_name='Luftfeuchtigkeit')),
                ('giftig', models.BooleanField(default=False, verbose_name='giftig')),
                ('wasserbedarf', models.IntegerField(choices=[(1, 'sehr gering'), (2, 'gering'), (3, 'mittel'), (4, 'hoch'), (5, 'sehr hoch')], verbose_name='Wasserbedarf')),
                ('endwuchshoehe_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Endwuchshöhe in cm')),
                ('quelle', models.CharField(blank=True, help_text='Woher stammen die botanischen Angaben? Wird im Projektbericht belegt.', max_length=300, verbose_name='Quelle')),
                ('erstellt_von', models.ForeignKey(blank=True, help_text='Leer bei den Arten des mitgelieferten Katalogs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pflanzenarten', to=settings.AUTH_USER_MODEL, verbose_name='angelegt von')),
                ('geeignete_bodenarten', models.ManyToManyField(related_name='pflanzenarten', to='plants.bodenart', verbose_name='geeignete Bodenarten')),
            ],
            options={
                'verbose_name': 'Pflanzenart',
                'verbose_name_plural': 'Pflanzenarten',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pflanze',
            name='art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pflanzen', to='plants.pflanzenart', verbose_name='Pflanzenart'),
            preserve_default=False,
        ),
    ]
