# Generated by Django 5.2.17 on 2026-09-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_bodenart_options_alter_pflanze_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pflegeempfehlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taetigkeit', models.CharField(choices=[('giessen', 'Gießen'), ('duengen', 'Düngen'), ('umtopfen', 'Umtopfen'), ('schneiden', 'Zurückschneiden'), ('vermehren', 'Vermehren')], max_length=15, verbose_name='Tätigkeit')),
                ('intervall_tage', models.PositiveIntegerField(verbose_name='Intervall in Tagen')),
                ('hinweis', models.CharField(blank=True, max_length=200, verbose_name='Hinweis')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pflegeempfehlungen', to='plants.pflanzenart')),
            ],
            options={
                'verbose_name': 'Pflegeempfehlung',
                'verbose_name_plural': 'Pflegeempfehlungen',
                'ordering': ['art__name', 'taetigkeit'],
                'constraints': [models.UniqueConstraint(fields=('art', 'taetigkeit'), name='eine_empfehlung_je_art_und_taetigkeit')],
            },
        ),
    ]
