# Generated by Django 5.2.17 on 2026-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_pflegeempfehlung'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenart',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=100, verbose_name='Beschreibung'),
        ),
    ]
