# Generated by Django 5.2.17 on 2026-09-06 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_bodenart_beschreibung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pflegevorlage',
            options={'ordering': ['taetigkeit'], 'verbose_name': 'Pflegevorlage', 'verbose_name_plural': 'Pflegevorlagen'},
        ),
        migrations.AddConstraint(
            model_name='pflanze',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('standort__isnull', True), ('status', 'wunsch')), models.Q(('standort__isnull', False), ('status', 'bestand')), _connector='OR'), name='standort_nur_bei_pflanzen_im_bestand'),
        ),
        migrations.AddConstraint(
            model_name='pflegevorlage',
            constraint=models.UniqueConstraint(fields=('pflanze', 'taetigkeit'), name='eine_vorlage_je_pflanze_und_taetigkeit'),
        ),
    ]
