# Generated by Django 5.2.17 on 2026-09-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_pflegevorlage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pflanze',
            name='standort',
            field=models.ForeignKey(blank=True, help_text='Nur bei Pflanzen im Bestand gesetzt.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pflanzen', to='plants.standort', verbose_name='Standort'),
        ),
    ]
